apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_DATABASE: mydatabase
  MYSQL_USER: myuser
  my.cnf: |
    [mysqld]
    max_connections = 200
    sql_mode = STRICT_TRANS_TABLES
    innodb_buffer_pool_size = 256M

